package com.example.demo.enums;

public enum TimelineEventType {
    CASE_CREATED,
    INTAKE_STARTED,
    INTAKE_COMPLETED,
    INVESTIGATION_STARTED,
    INVESTIGATION_COMPLETED,
    RISK_EVALUATION_STARTED,
    RISK_EVALUATION_COMPLETED,
    RECOMMENDATION_GENERATED,
    ANALYST_NOTE_GENERATED,
    CUSTOMER_RESPONSE_GENERATED,
    PENDING_ANALYST_REVIEW,
    ANALYST_REVIEW_SUBMITTED,
    CASE_APPROVED,
    CASE_CLOSED,
    CASE_ESCALATED
}
